services:
  - type: web
    name: bengali-asr-api
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "pip install --upgrade pip && pip install fastapi uvicorn python-multipart"
    startCommand: "uvicorn inference.demo_server:app --host 0.0.0.0 --port $PORT --workers 1"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PYTHONUNBUFFERED
        value: 1
