version: '3.8'

services:
  bengali-asr-gpu:
    build:
      context: ..
      dockerfile: inference/Dockerfile.gpu
    container_name: bengali-asr-gpu
    ports:
      - "8000:8000"
    volumes:
      - ../models:/app/models:ro
      - ./logs:/app/logs
    environment:
      - MODEL_PATH=/app/models/wav2vec2_bengali/checkpoint-best
      - MODEL_TYPE=wav2vec2
      - LOG_LEVEL=info
      - CUDA_VISIBLE_DEVICES=0
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
